-- Create the table for storing bias reports
create table public.bias_reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  ai_model text,
  bias_category text,
  evidence_text text
);

-- Set up Row Level Security (RLS)
-- For now, we enable read access for everyone, but only authenticated users or anon (if configured) can insert.
-- Since we are just starting, we will allow public inserts for testing ease, but this should be locked down later.

alter table public.bias_reports enable row level security;

-- Policy to allow anyone to read reports (public)
create policy "Allow public read access"
on public.bias_reports
for select
to public
using (true);

-- Policy to allow anonymous/public inserts (for this MVP phase)
create policy "Allow public insert access"
on public.bias_reports
for insert
to public
with check (true);
