-- 1. Create the 'observations' table
create table public.observations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  prompt text not null,
  model text not null,
  gender_bias text not null,
  notes text,
  image_url text
);

-- 2. Enable Realtime
alter publication supabase_realtime add table observations;

-- 3. Set up Row Level Security (RLS)
alter table public.observations enable row level security;

create policy "Allow public read access" on public.observations for select to public using (true);
create policy "Allow public insert access" on public.observations for insert to public with check (true);

-- 4. Storage configuration for 'observations' bucket
-- Note: You must first create the bucket 'observations' in the Supabase UI
-- These policies allow public access to the bucket.

insert into storage.buckets (id, name, public) 
values ('observations', 'observations', true)
on conflict (id) do nothing;

create policy "Public Access" on storage.objects for select to public using (bucket_id = 'observations');
create policy "Public Insert" on storage.objects for insert to public with check (bucket_id = 'observations');
