-- Create a table for app configuration (API keys, admin passcode, etc.)
create table if not exists public.app_config (
  id bigint generated by default as identity primary key,
  config_key text unique not null,
  config_value text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.app_config enable row level security;

-- Policies
-- 1. Allow public to read config (needed for checking passcode and fetching API keys in frontend if necessary)
-- Note: In a production app, you might want to be more careful with API keys.
create policy "Allow public read access" on public.app_config for select to public using (true);

-- 2. Allow public to insert/update (for initial setup and admin panel)
-- In a real app, this would be restricted to authenticated admins.
create policy "Allow public insert access" on public.app_config for insert to public with check (true);
create policy "Allow public update access" on public.app_config for update to public using (true);

-- Insert initial configurations
insert into public.app_config (config_key, config_value)
values 
  ('ADMIN_PASSCODE', 'apg2026'),
  ('GENERATION_ENABLED', 'true')
on conflict (config_key) do nothing;
